In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('TN_K_DRAMA_CST_AUDERT_INFO_202112.csv')

In [18]:
df.head(2)

,BRDCST_DE,BRDCST_END_DE,CHNNEL_NM,PROGRM_BEGIN_TIME,PROGRM_END_TIME,PROGRM_NM,PROGRM_DC,BRDCST_TME_NM,PROGRM_BRDCST_AREA_NM,BRDCST_TIME,...,MALE_N50S_WTCHNG_RT,MALE_N60S_ABOVE_WTCHNG_RT,FEMALE_4_9YO_WTCHNG_RT,FEMALE_N10S_WTCHNG_RT,FEMALE_N20S_WTCHNG_RT,FEMALE_N30S_WTCHNG_RT,FEMALE_N40S_WTCHNG_RT,FEMALE_N50S_WTCHNG_RT,FEMALE_N60S_ABOVE_WTCHNG_RT,CST_CN
0,20211201,20211201,KBS1,203126,205920,국가대표와이프,NaN,NaN,전국,2754,...,3.34685,11.12661,1.95276,0.78907,0.98699,1.78064,3.11222,6.11643,10.73837,"서초희역:한다감,강남구역:한상진,서강림역:심지호,나선덕역:금보라,오장금역:양미경,오..."
1,20211201,20211201,KBS2,92342,95134,국가대표와이프,NaN,NaN,전국,2752,...,0.13221,1.66102,0.08754,1.22335,0.02621,0.02083,1.39739,0.58369,1.63930,"서초희역:한다감,강남구역:한상진,서강림역:심지호,나선덕역:금보라,오장금역:양미경,오..."

In [17]:
df_col = pd.read_excel("K-드라마 프로그램 출연진정보 채_컬럼정의서.xls",
                       usecols = "B,C")
df_col

                          컬럼영문명       컬럼한글명
0                     BRDCST_DE        방송일자
1                 BRDCST_END_DE      방송종료일자
2                     CHNNEL_NM         채널명
3             PROGRM_BEGIN_TIME    프로그램시작시간
4               PROGRM_END_TIME    프로그램종료시간
5                     PROGRM_NM       프로그램명
6                     PROGRM_DC      프로그램설명
7                 BRDCST_TME_NM       방송회차명
8         PROGRM_BRDCST_AREA_NM   프로그램방송지역명
9                   BRDCST_TIME        방송시간
10        PROGRM_GENRE_LCLAS_NM  프로그램장르대분류명
11        PROGRM_GENRE_MLSFC_NM  프로그램장르중분류명
12        PROGRM_GENRE_SCLAS_NM  프로그램장르소분류명
13         MALE_4_9YO_WTCHNG_RT   남자4_9세시청율
14          MALE_N10S_WTCHNG_RT    남자10대시청율
15          MALE_N20S_WTCHNG_RT    남자20대시청율
16          MALE_N30S_WTCHNG_RT    남자30대시청율
17          MALE_N40S_WTCHNG_RT    남자40대시청율
18          MALE_N50S_WTCHNG_RT    남자50대시청율
19    MALE_N60S_ABOVE_WTCHNG_RT  남자60대이상시청율
20       FEMALE_4_9YO_WTCHNG_RT   여자4_9세시청율
21        FEMALE_N10S_WTCHNG_RT    여자10대시청율
22        FEMALE_N20S_WTCHNG_RT    여자20대시청율
23        FEMALE_N30S_WTCHNG_RT    여자30대시청율
24        FEMALE_N40S_WTCHNG_RT    여자40대시청율
25        FEMALE_N50S_WTCHNG_RT    여자50대시청율
26  FEMALE_N60S_ABOVE_WTCHNG_RT  여자60대이상시청율
27                       CST_CN       출연진내용

In [20]:
df_col_list = df_col.to_dict("records")

new_dic ={}
for dic_kv in df_col_list:
    new_dic[dic_kv['컬럼영문명']]=dic_kv['컬럼한글명']

df_kor = df.rename(columns = new_dic)
df_kor.head(1)

,방송일자,방송종료일자,채널명,프로그램시작시간,프로그램종료시간,프로그램명,프로그램설명,방송회차명,프로그램방송지역명,방송시간,...,남자50대시청율,남자60대이상시청율,여자4_9세시청율,여자10대시청율,여자20대시청율,여자30대시청율,여자40대시청율,여자50대시청율,여자60대이상시청율,출연진내용
0,20211201,20211201,KBS1,203126,205920,국가대표와이프,NaN,NaN,전국,2754,...,3.34685,11.12661,1.95276,0.78907,0.98699,1.78064,3.11222,6.11643,10.73837,"서초희역:한다감,강남구역:한상진,서강림역:심지호,나선덕역:금보라,오장금역:양미경,오..."